steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/order-api", "."]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "order-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/order-api"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "SQL_URL=$$SQL_URL,TWILIO_SID=$$TWILIO_SID,TWILIO_AUTH_TOKEN=$$TWILIO_AUTH_TOKEN,TWILIO_PHONE=$$TWILIO_PHONE"

substitutions:
  _SQL_URL: ""
  _TWILIO_SID: ""
  _TWILIO_AUTH_TOKEN: ""
  _TWILIO_PHONE: ""

images:
  - "gcr.io/$PROJECT_ID/order-api"
